# Site settings
title: Shannon Sullivan
tagline: "UX Researcher & Strategist"
url: "http://shansul.com" # The base hostname & protocol for your site. Use it if you need absolute URL's
permalink: :title.html

# Social
socialimg: /img/my-picture.jpg

# Contact
phone: 
email: 

# Use this for production
#sass:
#    style: :compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]